site_name: 防區狀況三生效－驗證精實案
theme: 
  name: readthedocs
  locale: 'zh_TW'
extra:
  search:
    language: 'jp'
nav:
  - '序': 'index.md'
  - '第一部—防區 民國八十八年1月—7月':
    - '01.md'
    - '02.md'
    - '03.md'
    - '04.md'
    - '05.md'
    - '06.md'
    - '07.md'
    - '08.md'
    - '09.md'
    - '23.md'
  - '第二部—正義 民國八十八年7月—12月':
    - '10.md'
    - '11.md'
    - '12.md'
    - '13.md'
    - '14.md'
  - '第三部—少年 民國八十九年—':
    - '15_0.md'
    - '15_1.md'
    - '21.md'
  - '附錄':
    - '22.md'